version: '2'
services:
  back:
    build:
      context: deploy/local
      dockerfile: app.docker
    environment:
      - "FRONT_URL=${FRONT_URL}"
      - "DB_USER=postgres"
      - "DEBUG=True"
    command: python manage.py runserver 0.0.0.0:8000
    # command: python -m debugpy --listen 0.0.0.0:3000 manage.py runserver 0.0.0.0:8000
    working_dir: /var/www
    # stdin_open: true
    # tty: true
    volumes:
      - ./back:/var/www
    ports:
      - "8000:8000"
      - "3000:3000"
  database:
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=db"
    ports:
      - "54321:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data/
  front:
    image: node:16-alpine
    environment:
      - "VUE_APP_API_URL=http://localhost"
      - "VUE_APP_API_PORT=8000"
    command: npm run serve
    # stdin_open: true
    # tty: true
    volumes:
      - ./front:/var/www
    ports:
      - "80:8080"
      # - "3000:3000"
volumes:
    pgdata_local:
