# Generated by Django 4.0.3 on 2022-03-24 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='readed_users',
            field=models.ManyToManyField(related_name='readed_rss_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
