# Generated by Django 4.0.3 on 2022-03-23 18:33

import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_country'),
    ]

    operations = [
        CryptoExtension(),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('upwork_id', models.CharField(default='', max_length=255, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='rss.country')),
                ('rss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss', to='rss.upwork')),
            ],
        ),
        migrations.RunSQL(
            sql='ALTER TABLE rss_job ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID();',
            reverse_sql='ALTER TABLE rss_job ALTER COLUMN id DROP DEFAULT',
        ),
    ]
