# Generated by Django 4.0.3 on 2022-03-24 00:06

import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('upwork_id', models.CharField(default='', max_length=255, null=True)),
                ('rate_from', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('rate_to', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='rss.country')),
                ('rss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss', to='rss.upwork')),
            ],
        ),
    ]
