# Generated by Django 4.0.3 on 2022-03-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('upwork_id', models.CharField(default='', max_length=255, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='rss.country')),
                ('rss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss', to='rss.upwork')),
            ],
        ),
    ]
