# Generated by Django 4.0.3 on 2022-03-25 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0003_job_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFavouritedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='favourited_users',
            field=models.ManyToManyField(related_name='favourited_rss_jobs', through='rss.JobFavouritedUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobfavouritedusers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.job'),
        ),
        migrations.AddField(
            model_name='jobfavouritedusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
