# Generated by Django 4.0.3 on 2022-04-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_alter_jobfavouritedusers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='upwork',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
