# Generated by Django 4.0.3 on 2022-04-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_upwork_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='rss.country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='rss.upwork'),
        ),
    ]
