# Generated by Django 4.0.3 on 2022-04-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_alter_job_country_alter_job_rss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfavouritedusers',
            old_name='group',
            new_name='job',
        ),
    ]
