# Generated by Django 4.0.3 on 2022-06-23 21:42

import django.contrib.postgres.search
from django.db import migrations
from django.db import connection


def set_generated(apps, schema_editor):
    query = """ALTER TABLE public.rss_job
        DROP COLUMN search_vector;
        ALTER TABLE public.rss_job 
            ADD COLUMN search_vector tsvector 
                GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce("content", ''))) STORED;"""

    with connection.cursor() as cursor:
        cursor.execute(query)

def reverse_generated(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_alter_jobfavouritedusers_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),

        migrations.RunPython(set_generated, reverse_generated),
    ]
